// ── bgws/realtime/engine/options.ts ────────────────────────────────────────
// What a unit may be told to do next. Generated by the rules, like the turn
// game's options, so a decider chooses among legal orders and cannot invent
// one.

import { distanceM, type LatLng } from "../../lib/board";
import { sightingOf, type ForceElement } from "../../lib/state";
import { inCover } from "../../lib/proceduralTerrain";
import { fireOdds } from "../../rules/jevState";
import { isFlankShot, weaponFor } from "../../rules/turnLoop";
import { canHit, describeOrder, knownEnemies, knownTo } from "./engine";
import { compass, positionsFor } from "./geometry";
import type { RtConfig, RtOption, RtState } from "./types";

/** Objective within this is "reached": no point offering to advance on it. */
const ON_OBJECTIVE_M = 300;
/** Held ground within this is "on position". */
const ON_POSITION_M = 150;
/** An assault is offered on enemies within this. */
const ASSAULT_RANGE_M = 1500;

/**
 * The enemy as this side can judge it: morale unknown (assumed steady), armour
 * unknown until identified. Same rule as the turn game's odds.
 */
export function perceived(enemy: ForceElement, identified: boolean): ForceElement {
  return {
    ...enemy,
    morale: "good",
    combatStrength: enemy.combatStrengthStart,
    armour: identified ? enemy.armour : undefined,
    armourMm: identified ? enemy.armourMm : undefined,
  };
}

/** The odds of `self` hitting `enemy` right now, as this side would estimate them. */
export function oddsAgainst(
  self: ForceElement,
  enemy: ForceElement,
  state: RtState,
  config: RtConfig,
): { pHit: number; expectedHits: number } | null {
  const rangeM = distanceM(self.position, enemy.position);
  const weapon = weaponFor(self, enemy, rangeM);
  if (!weapon) return null;
  const odds = fireOdds(
    [self],
    perceived(
      enemy,
      state.units[self.id]
        ? knownTo(state.game, state.units, self.id, enemy.id) === "full"
        : sightingOf(state.game, self.side, enemy.id) === "full",
    ),
    {
      rangeM,
      maxRangeM: weapon.maxRangeM,
      penetrationMm: weapon.penetrationMm,
      munition: weapon.munition,
      topAttack: weapon.topAttack,
      targetInCover: inCover(config.terrain, enemy.position),
      flank: isFlankShot([self], enemy, config.ruleset),
    },
    config.ruleset,
  );
  return { pHit: odds.pHit, expectedHits: odds.expectedHits };
}

/** Every order this unit may be given now. "keep" is always first. */
export function optionsFor(state: RtState, id: string, config: RtConfig): RtOption[] {
  const self = state.game.forceElements[id];
  const unit = state.units[id];
  if (!self || !unit || self.combatStrength <= 0) return [];
  const where = (at: LatLng) => `${Math.round(distanceM(self.position, at))} m ${compass(self.position, at)}`;

  const keep =
    unit.order.kind === "move"
      ? `carry on ${describeOrder(unit.order)} (${Math.round(distanceM(self.position, unit.order.to))} m to go; ` +
        (unit.order.mode === "march"
          ? "does not fire on the move)"
          : unit.order.mode === "assault"
            ? "firing at anything on the move)"
            : `fires on the move only ${unit.roe === "never" ? "never" : `if ${unit.roe}`}, at a penalty)`)
      : `carry on (${describeOrder(unit.order)})`;
  const options: RtOption[] = [{ id: "keep", summary: keep, order: unit.order }];

  // Back to what it is for.
  const { mission } = unit;
  if (mission.task === "take" && mission.at) {
    options.push(
      distanceM(self.position, mission.at) > ON_OBJECTIVE_M
        ? {
            id: "resume",
            summary: `resume the mission: ${mission.purpose}, moving tactically (${where(mission.at)})`,
            order: { kind: "move", to: mission.at, mode: "tactical" },
          }
        : { id: "resume", summary: `resume the mission: ${mission.purpose}, watching from it`, order: { kind: "overwatch" } },
    );
  } else if (mission.at && distanceM(self.position, mission.at) > ON_POSITION_M) {
    options.push({
      id: "resume",
      summary: `resume the mission: back to ${mission.purpose} (${where(mission.at)})`,
      order: { kind: "move", to: mission.at, mode: "tactical" },
    });
  } else if (unit.order.kind !== "overwatch") {
    options.push({ id: "resume", summary: `resume the mission: ${mission.purpose}, on overwatch`, order: { kind: "overwatch" } });
  }

  if (unit.order.kind !== "hold") {
    options.push({ id: "hold", summary: "halt and hold here", order: { kind: "hold" } });
  }
  if (unit.order.kind !== "overwatch") {
    options.push({
      id: "overwatch",
      summary: "stay here on overwatch: fire at anything in reach",
      order: { kind: "overwatch" },
    });
  }

  const known = knownEnemies(state, id);
  const broken = (enemyId: string) => state.units[enemyId]?.cohesion === "broken";

  for (const enemy of known) {
    const identified = knownTo(state.game, state.units, id, enemy.id) === "full";
    const name = `${identified ? enemy.label : "the contact"} ${enemy.id}`;
    const range = distanceM(self.position, enemy.position);
    if (canHit(self, enemy, enemy.position, config) && !(unit.order.kind === "engage" && unit.order.targetId === enemy.id)) {
      const odds = oddsAgainst(self, enemy, state, config);
      options.push({
        id: `engage:${enemy.id}`,
        summary: `halt and engage ${name} at ${Math.round(range)} m` + (odds ? ` (${Math.round(odds.pHit * 100)}% to hit)` : ""),
        order: { kind: "engage", targetId: enemy.id },
      });
    }
    // A broken enemy seen falling back is there to be followed up.
    if (identified && broken(enemy.id)) {
      options.push({
        id: `pursue:${enemy.id}`,
        summary: `pursue ${name}, which has broken: assault after it, firing on the move (${where(enemy.position)})`,
        order: { kind: "move", to: enemy.position, mode: "assault" },
      });
    } else if (range <= ASSAULT_RANGE_M) {
      options.push({
        id: `assault:${enemy.id}`,
        summary: `assault ${name}: close in firing at anything, to point-blank (${where(enemy.position)})`,
        order: { kind: "move", to: enemy.position, mode: "assault" },
      });
    }
  }
  if (known.some((enemy) => broken(enemy.id))) {
    options.push({
      id: "consolidate",
      summary: "consolidate: stop here on overwatch rather than follow the broken enemy",
      order: { kind: "overwatch" },
    });
  }

  for (const position of positionsFor(self, known, config)) {
    options.push({
      id: `pos:${position.purpose}`,
      summary: position.summary,
      order:
        position.purpose === "withdraw"
          ? { kind: "withdraw", to: position.at }
          : { kind: "move", to: position.at, mode: "tactical" },
    });
  }

  const objective = state.game.objectives?.[self.side];
  if (objective && distanceM(self.position, objective) > ON_OBJECTIVE_M) {
    const to = where(objective);
    options.push(
      {
        id: "objective",
        summary: `advance on the objective, tactically: slower, firing within the ROE (${to})`,
        order: { kind: "move", to: objective, mode: "tactical" },
      },
      {
        id: "objective:march",
        summary: `road-march to the objective: fastest, not firing on the move (${to})`,
        order: { kind: "move", to: objective, mode: "march" },
      },
      {
        id: "objective:bound",
        summary: `bound towards the objective: short moves, covering between them with a partner (${to})`,
        order: { kind: "move", to: objective, mode: "bound" },
      },
    );
  }

  return options;
}
