// ── bgws/realtime/engine/options.ts ────────────────────────────────────────
// What a unit may be told to do next. Generated by the rules, like the turn
// game's options, so a decider chooses among legal orders and cannot invent
// one.

import { distanceM } from "../../lib/board";
import { forceElementsOf, opposing, sightingOf, type ForceElement } from "../../lib/state";
import { inCover } from "../../lib/proceduralTerrain";
import { fireOdds } from "../../rules/jevState";
import { isFlankShot, weaponFor } from "../../rules/turnLoop";
import { canHit, describeOrder } from "./engine";
import { compass, positionsFor } from "./geometry";
import type { RtConfig, RtOption, RtState } from "./types";

/** Objective within this is "reached": no point offering to advance on it. */
const ON_OBJECTIVE_M = 300;

/**
 * The enemy as this side can judge it: morale unknown (assumed steady), armour
 * unknown until identified. Same rule as the turn game's odds.
 */
export function perceived(enemy: ForceElement, identified: boolean): ForceElement {
  return {
    ...enemy,
    morale: "good",
    combatStrength: enemy.combatStrengthStart,
    armour: identified ? enemy.armour : undefined,
    armourMm: identified ? enemy.armourMm : undefined,
  };
}

/** The odds of `self` hitting `enemy` right now, as this side would estimate them. */
export function oddsAgainst(
  self: ForceElement,
  enemy: ForceElement,
  state: RtState,
  config: RtConfig,
): { pHit: number; expectedHits: number } | null {
  const rangeM = distanceM(self.position, enemy.position);
  const weapon = weaponFor(self, enemy, rangeM);
  if (!weapon) return null;
  const odds = fireOdds(
    [self],
    perceived(enemy, sightingOf(state.game, self.side, enemy.id) === "full"),
    {
      rangeM,
      maxRangeM: weapon.maxRangeM,
      penetrationMm: weapon.penetrationMm,
      munition: weapon.munition,
      topAttack: weapon.topAttack,
      targetInCover: inCover(config.terrain, enemy.position),
      flank: isFlankShot([self], enemy, config.ruleset),
    },
    config.ruleset,
  );
  return { pHit: odds.pHit, expectedHits: odds.expectedHits };
}

/** Every order this unit may be given now. "keep" is always first. */
export function optionsFor(state: RtState, id: string, config: RtConfig): RtOption[] {
  const self = state.game.forceElements[id];
  const unit = state.units[id];
  if (!self || !unit || self.combatStrength <= 0) return [];

  const keep =
    unit.order.kind === "move"
      ? `carry on moving (${Math.round(distanceM(self.position, unit.order.to))} m to go; ` +
        `fires on the move only ${unit.roe === "never" ? "never" : `if ${unit.roe}`}, at a penalty)`
      : `carry on (${describeOrder(unit.order)})`;
  const options: RtOption[] = [{ id: "keep", summary: keep, order: unit.order }];
  if (unit.order.kind !== "hold") {
    options.push({ id: "hold", summary: "halt and hold here", order: { kind: "hold" } });
  }
  if (unit.order.kind !== "overwatch") {
    options.push({
      id: "overwatch",
      summary: "stay here on overwatch: fire at anything in reach",
      order: { kind: "overwatch" },
    });
  }

  const known = forceElementsOf(state.game, opposing(self.side)).filter(
    (enemy) => enemy.combatStrength > 0 && sightingOf(state.game, self.side, enemy.id) !== "none",
  );

  for (const enemy of known) {
    if (!canHit(self, enemy, enemy.position, config)) continue;
    if (unit.order.kind === "engage" && unit.order.targetId === enemy.id) continue;
    const odds = oddsAgainst(self, enemy, state, config);
    const identified = sightingOf(state.game, self.side, enemy.id) === "full";
    options.push({
      id: `engage:${enemy.id}`,
      summary:
        `halt and engage ${identified ? enemy.label : "the contact"} ${enemy.id} at ` +
        `${Math.round(distanceM(self.position, enemy.position))} m` +
        (odds ? ` (${Math.round(odds.pHit * 100)}% to hit)` : ""),
      order: { kind: "engage", targetId: enemy.id },
    });
  }

  for (const position of positionsFor(self, known, config)) {
    options.push({
      id: `pos:${position.purpose}`,
      summary: position.summary,
      order:
        position.purpose === "withdraw"
          ? { kind: "withdraw", to: position.at }
          : { kind: "move", to: position.at },
    });
  }

  const objective = state.game.objectives?.[self.side];
  if (objective && distanceM(self.position, objective) > ON_OBJECTIVE_M) {
    options.push({
      id: "objective",
      summary: `advance on the objective (${Math.round(distanceM(self.position, objective))} m ${compass(self.position, objective)})`,
      order: { kind: "move", to: objective },
    });
  }

  return options;
}
