/**
 * BGWS LLM COMMANDERS
 *
 * A language model given command of one side in a turn-based wargame, exposed
 * as a Query so the Mapplications app can execute it.
 *
 * WHY THIS REPOSITORY SITS HERE
 *
 * Next to [NXG] Mapplications Repo, in the same project, on the GOTHAM DEMO
 * ONTOLOGY (cc5e8302). That is not filing tidiness — it is the whole reason
 * this works.
 *
 * A query is resolved by api name WITHIN an ontology. The app's OSDK client is
 * created with `$ontologyRid` from its generated SDK, which is cc5e8302. A
 * first attempt put these commanders in a repository under a different
 * namespace whose ontology is the Accenture Ontology (e2ec7344). Three things
 * followed, in order:
 *
 *   - a bare @Query() published no api name, so the app got 404 QueryNotFound;
 *   - adding an api name required an Ontology import;
 *   - importing an object type from cc5e8302 from THERE failed to publish with
 *     ViewOntologyPermissionDenied, because that repository had no rights over
 *     the app's ontology.
 *
 * Put the function in the app's ontology and all three disappear.
 *
 * WHAT THIS FUNCTION DELIBERATELY DOES NOT DO
 *
 * Know the rules. It is a thin pipe: prompt in, raw completion out. It does
 * not decide what is legal and does not parse the reply.
 *
 * The rules live in the app (src/apps/bgws/rules), which generates every legal
 * option for every element and DISCARDS anything the model returns that is not
 * on that list. So a model cannot invent a move, only choose badly; the prompt
 * and parser stay pure and unit tested without ever calling a model; and
 * swapping models is a parameter rather than a rewrite. If this function grew
 * rules of its own, the game would have two sources of truth about what is
 * legal.
 *
 * WHY TWO MODELS
 *
 * Different models commanding opposing sides is the experiment, not a gimmick.
 * The harness already measures whether a MECHANIC earns its place; the same
 * method measures whether a COMMANDER does.
 */

import { Query, UserFacingError } from "@foundry/functions-api";
// Model imports are added through Resource Imports, not by hand.
import {
    AnthropicClaude_4_6_Sonnet,
    GPT_5_2,
} from "@foundry/models-api/language-models";

/**
 * Which model commands. A narrow union rather than a free model name, so an
 * unknown value fails loudly at the boundary instead of silently falling back
 * to a default nobody chose.
 */
export type CommanderModel = "claude-sonnet-4-6" | "gpt-5-2";

const MODELS: CommanderModel[] = ["claude-sonnet-4-6", "gpt-5-2"];

/**
 * Temperature 0.
 *
 * A wargame commander should be reproducible: the same board, the same seed
 * and the same prompt ought to give the same orders, or a batch comparing two
 * rulesets is also comparing two moods.
 */
const TEMPERATURE = 0;

/**
 * Enough for orders for a dozen elements with a sentence of reasoning each.
 *
 * Too small is the failure mode that matters: a truncated reply is unreadable
 * JSON, the side holds position, and it reads as a cautious commander rather
 * than a clipped one.
 */
const MAX_TOKENS = 2000;

const SYSTEM_BRIEF = [
    "You are a sub-unit commander in a turn-based wargame at platoon and troop level.",
    "",
    "You will be given what your side can see, and every legal option for every",
    "element you command. Options are generated by the rules engine: they are the",
    "only moves available to you. Anything you reply that is not on that list is",
    "discarded and that element does nothing, so choose only from the ids given.",
    "",
    "Sound tactical practice, in rough priority:",
    "- concentrate fire rather than spreading it across many targets;",
    "- engage from short range where the modifiers favour you, and close if you are not there;",
    "- do not advance broken or disrupted elements into contact;",
    "- keep your HQ alive: it is what lets you commit elements at all;",
    "- an element with nothing useful to do should hold rather than expose itself.",
    "",
    "An element may be ordered to MOVE and then ENGAGE in the same turn. Both",
    "orders count as one element against your command capacity.",
    "",
    "Absence of a contact is not evidence of absence. You are seeing through fog of war.",
    "",
    "Reply with JSON only. No prose, no code fences, no explanation outside the JSON.",
].join("\n");

export class BgwsCommanderFunctions {
    /**
     * One side's orders for one turn.
     *
     * ⚠ @Query, NOT @Function. `@Function()` registers a function for use
     * INSIDE Foundry — Workshop, Actions, other functions — and publishes
     * nothing on the API gateway, so an app calling
     * /v2/functions/queries/{apiName}/execute gets a bare 400. Only @Query
     * creates an endpoint an application can execute.
     *
     * The api name is explicit and prefixed: the docs require it to be unique
     * across every imported Ontology, and "commanderTurn" is a name another
     * project in this ontology could plausibly want.
     *
     * @param prompt The board, the options and the reply format. Built by the
     *   app so the rules stay in one place; see rules/llmCommander.ts.
     * @param model Which model commands this side.
     * @param directive Optional mission or doctrine, so blue and red can be
     *   given different characters and the difference measured.
     */
    @Query({ apiName: "bgwsCommanderTurn" })
    public async commanderTurn(
        prompt: string,
        model: string,
        directive: string,
    ): Promise<string> {
        if (!prompt || prompt.trim().length === 0) {
            // Loud, not empty: an empty prompt would produce confident orders
            // about a board the model was never shown.
            throw new UserFacingError("No prompt was supplied, so there is nothing to command.");
        }

        const chosen = MODELS.find((candidate) => candidate === model);
        if (chosen === undefined) {
            throw new UserFacingError(
                `Unknown commander model "${model}". Available: ${MODELS.join(", ")}.`,
            );
        }

        const system = directive && directive.trim().length > 0
            ? `${SYSTEM_BRIEF}\n\nYOUR DIRECTIVE\n\n${directive.trim()}`
            : SYSTEM_BRIEF;

        // The brief is prepended to the user turn rather than sent as a SYSTEM
        // message, because the two imported models disagree about how a system
        // role is shaped and this function is not the place to care.
        const content = `${system}\n\n---\n\n${prompt}`;

        const completion = chosen === "claude-sonnet-4-6"
            ? await this.askClaude(content)
            : await this.askGpt(content);

        if (completion === undefined || completion.trim().length === 0) {
            // Returned as text rather than thrown: the app treats an unreadable
            // reply as "this side held position, and here is why", which keeps
            // a game alive through one bad response.
            return JSON.stringify({
                plan: "the model returned nothing",
                orders: [],
            });
        }

        return completion;
    }

    /** Every model this function will accept, for the app's picker. */
    @Query({ apiName: "bgwsCommanderModels" })
    public commanderModels(): string[] {
        return MODELS.slice();
    }

    /**
     * The two imported models do NOT share a response shape, which is why each
     * gets its own method rather than one generic call. Claude returns
     * `completion`; GPT returns `choices[0].message.content`. Casting over that
     * would move the breakage from compile time to the middle of a game.
     */
    private async askClaude(content: string): Promise<string | undefined> {
        const response = await AnthropicClaude_4_6_Sonnet.createGenericChatCompletion({
            params: { temperature: TEMPERATURE, maxTokens: MAX_TOKENS },
            messages: [{ role: "USER", contents: [{ text: content }] }],
        });
        return response.completion;
    }

    private async askGpt(content: string): Promise<string | undefined> {
        const response = await GPT_5_2.createChatCompletion({
            params: { temperature: TEMPERATURE, maxTokens: MAX_TOKENS },
            messages: [{ role: "USER", contents: [{ text: content }] }],
        });
        return response.choices.length > 0 ? response.choices[0].message.content : undefined;
    }
}
