/**
 * BGWS LLM COMMANDERS
 *
 * A language model given command of one side in a turn-based wargame, exposed
 * as a Query so the Mapplications app can execute it.
 *
 * WHY THIS REPOSITORY SITS HERE
 *
 * Next to [NXG] Mapplications Repo, in the same project, on the GOTHAM DEMO
 * ONTOLOGY (cc5e8302). That is not filing tidiness — it is the whole reason
 * this works.
 *
 * A query is resolved by api name WITHIN an ontology. The app's OSDK client is
 * created with `$ontologyRid` from its generated SDK, which is cc5e8302. A
 * first attempt put these commanders in a repository under a different
 * namespace whose ontology is the Accenture Ontology (e2ec7344). Three things
 * followed, in order:
 *
 *   - a bare @Query() published no api name, so the app got 404 QueryNotFound;
 *   - adding an api name required an Ontology import;
 *   - importing an object type from cc5e8302 from THERE failed to publish with
 *     ViewOntologyPermissionDenied, because that repository had no rights over
 *     the app's ontology.
 *
 * Put the function in the app's ontology and all three disappear.
 *
 * WHAT THIS FUNCTION DELIBERATELY DOES NOT DO
 *
 * Know the rules. It is a thin pipe: prompt in, raw completion out. It does
 * not decide what is legal and does not parse the reply.
 *
 * The rules live in the app (src/apps/bgws/rules), which generates every legal
 * option for every element and DISCARDS anything the model returns that is not
 * on that list. So a model cannot invent a move, only choose badly; the prompt
 * and parser stay pure and unit tested without ever calling a model; and
 * swapping models is a parameter rather than a rewrite. If this function grew
 * rules of its own, the game would have two sources of truth about what is
 * legal.
 *
 * WHY TWO MODELS
 *
 * Different models commanding opposing sides is the experiment, not a gimmick.
 * The harness already measures whether a MECHANIC earns its place; the same
 * method measures whether a COMMANDER does.
 *
 * WHY THREE QUERIES
 *
 *   bgwsCommanderTurn     orders for a turn, carried out EXACTLY as written.
 *                         Jev off.
 *   bgwsCommanderTurnJev  orders for a turn that Jev, a fast decision model,
 *                         will carry out — choosing which committed element
 *                         acts next, adapting an order when the board has
 *                         changed, and making reactive-fire and contact calls
 *                         at the moment. Jev on.
 *   bgwsCommanderDecide   one quick call Jev was unsure about, escalated to
 *                         the side's model mid-turn. Jev on.
 *
 * Separate queries rather than a flag on one, because the brief is what
 * differs and the brief is what a reader of this file needs to see. With Jev
 * on, the old brief is actively wrong: it tells the model its standing orders
 * are final and that its orders run as written, and neither is true.
 */

import { Query, UserFacingError } from "@foundry/functions-api";
// Model imports are added through Resource Imports, not by hand.
import {
    AnthropicClaude_4_6_Sonnet,
    GPT_5_2,
} from "@foundry/models-api/language-models";

/**
 * Which model commands. A narrow union rather than a free model name, so an
 * unknown value fails loudly at the boundary instead of silently falling back
 * to a default nobody chose.
 */
export type CommanderModel = "claude-sonnet-4-6" | "gpt-5-2";

const MODELS: CommanderModel[] = ["claude-sonnet-4-6", "gpt-5-2"];

/**
 * Temperature 0.
 *
 * A wargame commander should be reproducible: the same board, the same seed
 * and the same prompt ought to give the same orders, or a batch comparing two
 * rulesets is also comparing two moods.
 */
const TEMPERATURE = 0;

/**
 * Enough for orders for a dozen elements with a sentence of reasoning each.
 *
 * Too small is the failure mode that matters: a truncated reply is unreadable
 * JSON, the side holds position, and it reads as a cautious commander rather
 * than a clipped one.
 */
const MAX_TOKENS = 2000;

/**
 * With Jev on, a model that reasons before answering needs the room: GPT-5.2
 * may count hidden reasoning against the limit, and a reply cut short is
 * unreadable JSON — an unanswered turn. A higher ceiling costs nothing unless
 * it is used.
 */
const MAX_TOKENS_JEV: Record<CommanderModel, number> = {
    "claude-sonnet-4-6": 3000,
    "gpt-5-2": 8000,
};

/** A single escalated decision: a key and one sentence. */
const MAX_TOKENS_DECIDE: Record<CommanderModel, number> = {
    "claude-sonnet-4-6": 300,
    "gpt-5-2": 2000,
};

const SYSTEM_BRIEF = [
    "You are a sub-unit commander in a turn-based wargame at platoon and troop level.",
    "",
    "You will be given what your side can see, and every legal option for every",
    "element you command. Options are generated by the rules engine: they are the",
    "only moves available to you. Anything you reply that is not on that list is",
    "discarded and that element does nothing, so choose only from the ids given.",
    "",
    "Sound tactical practice, in rough priority:",
    "- concentrate fire rather than spreading it across many targets;",
    "- engage from short range where the modifiers favour you, and close if you are not there;",
    "- do not advance broken or disrupted elements into contact;",
    "- keep your HQ alive: it is what lets you commit elements at all;",
    // Leave it out, not "hold": the app prompt says holding costs a whole
    // activation against command capacity and achieves nothing, and the two
    // briefs must not give the model opposite instructions.
    "- an element with nothing useful to do should be left out of your orders, not ordered to hold.",
    "",
    "An element may be ordered to MOVE and then ENGAGE in the same turn. Both",
    "orders count as one element against your command capacity.",
    "",
    "Absence of a contact is not evidence of absence. You are seeing through fog of war.",
    "",
    "Reply with JSON only. No prose, no code fences, no explanation outside the JSON.",
].join("\n");

/**
 * The brief when Jev carries the orders out.
 *
 * What changes, and why each line is there:
 *
 *   - ORDERS ARE INTENT. Jev picks which committed element acts next and may
 *     adapt an order to what has happened since. So the model's job moves up
 *     a level: say what each element is FOR, because that is what Jev reads
 *     when it adapts. A "why" that only restates the order gives it nothing.
 *   - COMMITTING IS STILL THE MODEL'S. Jev can only act with elements the
 *     orders commit; command capacity is spent here and nowhere else.
 *   - RULES OF ENGAGEMENT ARE DEFAULTS. Jev decides reactive fire at the
 *     moment and may depart from them — except "never", which it must obey.
 *     "never" is therefore how the model keeps an element hidden.
 *   - THE NEW OPTIONS AND THE ASSESSMENT ARE NAMED, so the model knows what a
 *     "moves 420 m NE to overwatch" option is and what the JEV ASSESSMENT
 *     table in the prompt means.
 */
const JEV_SYSTEM_BRIEF = [
    "You are the commander of one side in a turn-based wargame at platoon and troop level.",
    "",
    "You write the plan and the orders for this turn. A fast tactical controller",
    "(Jev) then fights the turn for you, one activation at a time. It:",
    "- chooses WHICH of your committed elements acts next, and when;",
    "- may ADAPT an element's order if the board has changed since you wrote it —",
    "  a target gone, a new threat, a better shot;",
    "- decides reactive fire and what a moving element does on contact or under",
    "  fire, at the moment it happens;",
    "- can only use elements your orders commit. Command capacity is spent by you.",
    "",
    "So your orders are INTENT, and the reasons matter as much as the choices:",
    "- `plan` names the main effort and what the rest are for.",
    "- every order's `why` says what that element is FOR — \"fix R1 so B3 can reach",
    "  its flank\", not \"B2 fires at R1\". Jev reads it when it has to adapt.",
    "- order the list by importance; it is also how you tell Jev what matters most.",
    "",
    "Options are generated by the rules engine: they are the only moves available.",
    "Anything you reply that is not on that list is discarded, so choose only from",
    "the ids given. Some move options are chosen for the ground — into cover, to",
    "overwatch, pulling back out of sight, onto a flank — and say so.",
    "",
    "Standing orders (rules of engagement) are DEFAULTS for Jev, which may depart",
    "from them at the moment. The exception is \"never\": Jev must obey it. Use",
    "\"never\" for an element you want kept hidden whatever happens.",
    "",
    "If the prompt includes a JEV ASSESSMENT, it is the controller's quick read of",
    "each element's danger and opportunity (1 low – 5 high). It is advice, not fact;",
    "the board is the fact.",
    "",
    "Sound tactical practice, in rough priority:",
    "- concentrate fire rather than spreading it across many targets;",
    "- engage from short range where the modifiers favour you, and close if you are not there;",
    "- do not advance broken or disrupted elements into contact;",
    "- keep your HQ alive: it is what lets you commit elements at all;",
    "- use the ground: an element in cover or on overwatch is worth more than one in the open;",
    "- an element with nothing useful to do should be left out of your orders, not ordered to hold.",
    "",
    "An element may be ordered to MOVE and then ENGAGE in the same turn. Both",
    "orders count as one element against your command capacity.",
    "",
    "Absence of a contact is not evidence of absence. You are seeing through fog of war.",
    "",
    "Reply with JSON only. No prose, no code fences, no explanation outside the JSON.",
].join("\n");

/**
 * The brief for one escalated decision.
 *
 * Short on purpose: the game is paused mid-activation waiting for this. The
 * prompt from the app already carries the situation, the directive and the
 * options with their keys; all this adds is who is asking and the reply rule.
 */
const DECIDE_BRIEF = [
    "You are the commander of one side in a turn-based wargame. Your fast tactical",
    "controller was unsure about the decision below and has passed it to you. The",
    "game is waiting on your answer.",
    "",
    "Choose exactly one of the option keys given. A key that was not offered is",
    "ignored and the rules decide instead.",
    "",
    'Reply with JSON only, on one line: {"choice":"<key>","why":"<one sentence>"}',
].join("\n");

export class BgwsCommanderFunctions {
    /**
     * One side's orders for one turn.
     *
     * ⚠ @Query, NOT @Function. `@Function()` registers a function for use
     * INSIDE Foundry — Workshop, Actions, other functions — and publishes
     * nothing on the API gateway, so an app calling
     * /v2/functions/queries/{apiName}/execute gets a bare 400. Only @Query
     * creates an endpoint an application can execute.
     *
     * The api name is explicit and prefixed: the docs require it to be unique
     * across every imported Ontology, and "commanderTurn" is a name another
     * project in this ontology could plausibly want.
     *
     * @param prompt The board, the options and the reply format. Built by the
     *   app so the rules stay in one place; see rules/llmCommander.ts.
     * @param model Which model commands this side.
     * @param directive Optional mission or doctrine, so blue and red can be
     *   given different characters and the difference measured.
     */
    @Query({ apiName: "bgwsCommanderTurn" })
    public async commanderTurn(
        prompt: string,
        model: string,
        directive: string,
    ): Promise<string> {
        if (!prompt || prompt.trim().length === 0) {
            // Loud, not empty: an empty prompt would produce confident orders
            // about a board the model was never shown.
            throw new UserFacingError("No prompt was supplied, so there is nothing to command.");
        }

        const chosen = this.modelFor(model);
        return this.run(chosen, this.compose(SYSTEM_BRIEF, directive, prompt), MAX_TOKENS);
    }

    /**
     * One side's orders for one turn, for Jev to carry out.
     *
     * Same contract as bgwsCommanderTurn — same parameters, same reply format,
     * parsed by the same code in the app. Only the brief differs; see
     * JEV_SYSTEM_BRIEF for what and why.
     */
    @Query({ apiName: "bgwsCommanderTurnJev" })
    public async commanderTurnJev(
        prompt: string,
        model: string,
        directive: string,
    ): Promise<string> {
        if (!prompt || prompt.trim().length === 0) {
            throw new UserFacingError("No prompt was supplied, so there is nothing to command.");
        }
        const chosen = this.modelFor(model);
        return this.run(
            chosen,
            this.compose(JEV_SYSTEM_BRIEF, directive, prompt),
            MAX_TOKENS_JEV[chosen],
        );
    }

    /**
     * One decision Jev was unsure about, escalated mid-turn.
     *
     * The app's prompt already includes the situation, the side's directive
     * and the keyed options, so `directive` is normally empty here — passing
     * it again would only say the same thing twice.
     *
     * Reply: {"choice":"<key>","why":"..."}. An empty or unreadable reply is
     * not an error: the app lets the rules decide and records that it did.
     */
    @Query({ apiName: "bgwsCommanderDecide" })
    public async commanderDecide(
        prompt: string,
        model: string,
        directive: string,
    ): Promise<string> {
        if (!prompt || prompt.trim().length === 0) {
            throw new UserFacingError("No decision was supplied, so there is nothing to decide.");
        }
        const chosen = this.modelFor(model);
        return this.run(
            chosen,
            this.compose(DECIDE_BRIEF, directive, prompt),
            MAX_TOKENS_DECIDE[chosen],
        );
    }

    /** A known model, or a loud error naming the ones that are. */
    private modelFor(model: string): CommanderModel {
        const chosen = MODELS.find((candidate) => candidate === model);
        if (chosen === undefined) {
            throw new UserFacingError(
                `Unknown commander model "${model}". Available: ${MODELS.join(", ")}.`,
            );
        }
        return chosen;
    }

    /**
     * Brief, directive and prompt, as one user turn.
     *
     * The brief is prepended to the user turn rather than sent as a SYSTEM
     * message, because the two imported models disagree about how a system
     * role is shaped and this function is not the place to care.
     */
    private compose(brief: string, directive: string, prompt: string): string {
        const system = directive && directive.trim().length > 0
            ? `${brief}\n\nYOUR DIRECTIVE\n\n${directive.trim()}`
            : brief;
        return `${system}\n\n---\n\n${prompt}`;
    }

    /**
     * Ask the chosen model, and return its reply as it came.
     *
     * ⚠ AN EMPTY REPLY IS RETURNED EMPTY, not dressed up as JSON. This used to
     * return {"plan":"the model returned nothing","orders":[]}, which the app
     * parsed as a real decision to do nothing — so a trial counted a silent
     * model as a turn played rather than a turn unanswered, which is exactly
     * the "unreachable model looks like a cautious general" error the trial
     * exists to catch. An empty string is read by the app as unanswered: the
     * side still holds position and the game goes on, and the failure is
     * counted.
     */
    private async run(chosen: CommanderModel, content: string, maxTokens: number): Promise<string> {
        const completion = chosen === "claude-sonnet-4-6"
            ? await this.askClaude(content, maxTokens)
            : await this.askGpt(content, maxTokens);
        return completion === undefined ? "" : completion;
    }

    /** Every model this function will accept, for the app's picker. */
    @Query({ apiName: "bgwsCommanderModels" })
    public commanderModels(): string[] {
        return MODELS.slice();
    }

    /**
     * The two imported models do NOT share a response shape, which is why each
     * gets its own method rather than one generic call. Claude returns
     * `completion`; GPT returns `choices[0].message.content`. Casting over that
     * would move the breakage from compile time to the middle of a game.
     */
    private async askClaude(content: string, maxTokens: number): Promise<string | undefined> {
        const response = await AnthropicClaude_4_6_Sonnet.createGenericChatCompletion({
            params: { temperature: TEMPERATURE, maxTokens },
            messages: [{ role: "USER", contents: [{ text: content }] }],
        });
        return response.completion;
    }

    private async askGpt(content: string, maxTokens: number): Promise<string | undefined> {
        const response = await GPT_5_2.createChatCompletion({
            params: { temperature: TEMPERATURE, maxTokens },
            messages: [{ role: "USER", contents: [{ text: content }] }],
        });
        return response.choices.length > 0 ? response.choices[0].message.content : undefined;
    }
}
