// ── bgws/rules/commanderTrial.ts ───────────────────────────────────────────
// Does a model command better than the bot?
//
// This is the question the platform was built to answer and the one nothing
// in reports/ has ever addressed. Everything else measures RULES against a
// fixed commander. This measures COMMANDERS against fixed rules.
//
// THREE THINGS IT HAS TO GET RIGHT, AND WHY
//
// 1. BOTH ORIENTATIONS, ALWAYS. Every seed is played twice, with the
//    challenger as blue and then as red. Blue and red are not symmetric in
//    any force list except the control, and this codebase has already been
//    caught once by a side bias it did not know about — a tie-break that fell
//    to blue gave it 24 wins to 10 in a supposedly symmetric control. A trial
//    that ran one orientation would measure the force list as much as the
//    commander.
//
// 2. FAILURES COUNTED SEPARATELY FROM LOSSES. A model that times out holds
//    position and loses. That is not the same finding as a model that played
//    and was outfought, and averaging them together would let an unreachable
//    endpoint masquerade as a cautious general.
//
// 3. REJECTED ORDERS COUNTED. Every option was generated by the rules, so an
//    order that is not on the list means the model asked for something
//    impossible. That rate is the difference between "played badly" and
//    "does not understand the board", and it is the most actionable number
//    here — it is a prompt problem, not an intelligence problem.
//
// The model call is injected, so this whole file is testable without a model.

import { advanceTurn, startGame, type LiveGame } from "../lib/liveGame";
import type { TerrainSampler } from "../lib/lineOfSight";
import type { GameState, Side } from "../lib/state";
import { opposing } from "../lib/state";
import { createRng } from "./dice";
import { EventLog } from "./events";
import type { OrdersCommander } from "./orders";
import type { RuleSet } from "./ruleset";

export interface TrialOptions {
  ruleset: RuleSet;
  terrain: TerrainSampler;
  /** A fresh starting state per game — never a shared mutable one. */
  scenario: () => GameState;
  seeds: string[];
  maxTurns?: number;
  /** The commander under test, usually a model. */
  challenger: (side: Side) => OrdersCommander;
  /** What it has to beat. */
  baseline: (side: Side) => OrdersCommander;
  /**
   * Called after each game, so a caller can show progress.
   *
   * A trial is a few hundred sequential model calls and takes tens of
   * minutes. Run from a browser with no sign of life it looks like a hung
   * tab, and somebody closes it twenty minutes in.
   */
  onProgress?: (finished: number, total: number, game: TrialGame) => void;
}

export interface TrialGame {
  seed: string;
  /** Which side the challenger played. Each seed is played as both. */
  challengerSide: Side;
  winner: "challenger" | "baseline" | null;
  turns: number;
  reason: "annihilation" | "turnLimit";
  /** Orders the challenger issued, and how many the rules refused. */
  ordersIssued: number;
  ordersRejected: number;
  /** Turns where the challenger could not answer at all. */
  failedTurns: number;
  /** The first failure, for the report. Usually they are all the same. */
  firstFailure?: string;
  /** What the challenger said it was doing, for reading afterwards. */
  plans: string[];
}

export interface TrialResult {
  games: TrialGame[];
  challengerWins: number;
  baselineWins: number;
  draws: number;
  meanTurns: number;
  ordersIssued: number;
  ordersRejected: number;
  /** Turns in which the challenger was unreachable or unreadable. */
  failedTurns: number;
  totalTurns: number;
}

/** One game. The challenger plays `challengerSide`. */
async function playOne(
  options: TrialOptions,
  seed: string,
  challengerSide: Side,
): Promise<TrialGame> {
  const baselineSide = opposing(challengerSide);
  const commanders = {
    [challengerSide]: options.challenger(challengerSide),
    [baselineSide]: options.baseline(baselineSide),
  } as Record<Side, OrdersCommander>;

  const log = new EventLog();
  let game: LiveGame = startGame(options.scenario());

  const config = {
    ruleset: options.ruleset,
    terrain: options.terrain,
    commanders,
    // The dice are seeded identically for both orientations, so the only
    // thing that differs between the pair is which commander sat on which
    // side. They diverge once a decision differs — that IS the measurement.
    rng: createRng(`${seed}:dice`),
    log,
    maxTurns: options.maxTurns ?? 40,
  };

  while (!game.over) game = await advanceTurn(game, config);

  let ordersIssued = 0;
  let ordersRejected = 0;
  let failedTurns = 0;
  let firstFailure: string | undefined;
  const plans: string[] = [];

  for (const turn of game.turns) {
    const orders = turn.orders[challengerSide];
    ordersIssued += orders.intents.length;
    ordersRejected += turn.rejected[challengerSide].length;
    if (orders.failure) {
      failedTurns += 1;
      firstFailure ??= orders.failure;
    }
    if (orders.plan) plans.push(orders.plan);
  }

  return {
    seed,
    challengerSide,
    winner:
      game.winner == null ? null : game.winner === challengerSide ? "challenger" : "baseline",
    turns: game.turns.length,
    reason: game.reason ?? "turnLimit",
    ordersIssued,
    ordersRejected,
    failedTurns,
    firstFailure,
    plans,
  };
}

/**
 * Play every seed in both orientations and tally the result.
 *
 * Sequential rather than parallel on purpose: a model commander is a network
 * call per side per turn, and firing a hundred of them at once is how a
 * trial turns into a rate-limit incident and then into a report full of
 * "unreachable" that says nothing about the model.
 */
export async function runTrial(options: TrialOptions): Promise<TrialResult> {
  const games: TrialGame[] = [];
  const total = options.seeds.length * 2;

  for (const seed of options.seeds) {
    for (const side of ["blue", "red"] as const) {
      const game = await playOne(options, seed, side);
      games.push(game);
      options.onProgress?.(games.length, total, game);
    }
  }

  return summarise(games);
}

export function summarise(games: TrialGame[]): TrialResult {
  const total = (pick: (game: TrialGame) => number) =>
    games.reduce((sum, game) => sum + pick(game), 0);

  return {
    games,
    challengerWins: games.filter((game) => game.winner === "challenger").length,
    baselineWins: games.filter((game) => game.winner === "baseline").length,
    draws: games.filter((game) => game.winner == null).length,
    meanTurns:
      games.length === 0 ? 0 : Math.round((total((game) => game.turns) / games.length) * 100) / 100,
    ordersIssued: total((game) => game.ordersIssued),
    ordersRejected: total((game) => game.ordersRejected),
    failedTurns: total((game) => game.failedTurns),
    totalTurns: total((game) => game.turns),
  };
}

/**
 * A readable verdict.
 *
 * ⚠ IT REFUSES TO CALL A RESULT WHEN THE MODEL DID NOT ANSWER. A trial in
 * which the challenger was unreachable for a fifth of its turns is a trial of
 * the network, and reporting "the bot won" from it would be the most
 * expensive kind of wrong: plausible, quotable, and about nothing.
 */
export function describeTrial(result: TrialResult, label: string): string {
  const played = result.games.length;
  const failureRate = result.totalTurns === 0 ? 0 : result.failedTurns / result.totalTurns;
  const rejectRate =
    result.ordersIssued === 0 ? 0 : result.ordersRejected / result.ordersIssued;

  const lines = [
    `${label} over ${played} games (${played / 2} seeds, both orientations)`,
    `  challenger ${result.challengerWins} · baseline ${result.baselineWins} · drawn ${result.draws}`,
    `  mean length ${result.meanTurns} turns`,
    `  orders ${result.ordersIssued} issued, ${result.ordersRejected} rejected by the rules ` +
      `(${Math.round(rejectRate * 100)}%)`,
    `  turns the challenger could not answer: ${result.failedTurns} of ${result.totalTurns} ` +
      `(${Math.round(failureRate * 100)}%)`,
  ];

  if (failureRate > 0.1) {
    lines.push(
      `  ⚠ NO VERDICT. The challenger failed to answer in ${Math.round(failureRate * 100)}% of ` +
        `turns, so this measures the connection and not the commander.`,
    );
  } else if (rejectRate > 0.25) {
    lines.push(
      `  ⚠ TREAT WITH CARE. ${Math.round(rejectRate * 100)}% of its orders were not legal ` +
        `options, which is a prompt problem before it is a judgement problem.`,
    );
  }

  return lines.join("\n");
}
