// ── bgws/rules/commander.ts ────────────────────────────────────────────────
// Who decides.
//
// One interface, three implementations eventually: a person, a scripted bot,
// and a language model. They are interchangeable because they are all handed
// the SAME thing — a SideView from the fog-of-war projection, plus the list of
// options the engine says are legal — and all return one choice.
//
// WHY THE BOT COMES FIRST
// -----------------------
// A scripted commander is not a placeholder for the model. It is the baseline
// the model is measured against, and without it "the AI played well" has no
// meaning. It is also free, instant and reproducible, which is what makes the
// experiment harness able to run a thousand games to ask whether a rule
// changes anything.
//
// The options are generated by the ENGINE, not by the commander. A commander
// that could invent its own options could invent illegal ones, and validating
// them afterwards is strictly harder than not offering them.

import { distanceM } from "../lib/board";
import type { PlannedRoute } from "../lib/routePlan";
import type { SideView } from "../lib/fogOfWar";
import type { Capability, Side } from "../lib/state";
import type { Rng } from "./dice";
import type { DecisionOption } from "./events";

export type ActionKind = "move" | "fire" | "assault" | "hold" | "pass";

/** A legal action the engine is willing to resolve. */
export interface ActionOption extends DecisionOption {
  kind: ActionKind;
  /** The force element acting. Absent for a pass. */
  actorId?: string;
  /**
   * Every element taking part, for a Combined Fire or Combined Assault
   * (9.2.1, 9.3). Absent means the one in `actorId` acts alone.
   *
   * `actorId` stays the LEAD element — the one whose activation pays for the
   * action and under whose entry the option is offered — so every existing
   * caller that reads `actorId` keeps working and an option list stays
   * grouped by the element a commander is thinking about.
   */
  actorIds?: string[];
  targetId?: string;
  destination?: { lat: number; lng: number };
  /**
   * The march this option commits the element to, as it will stand AFTER this
   * turn's movement. Absent on an ordinary bound.
   *
   * Carried on the option rather than worked out again during resolution so
   * that what the commander was offered and what the engine applies are the
   * same object — the alternative is two planners that can disagree.
   */
  route?: PlannedRoute;
  /**
   * What this element does if it makes contact while moving (7.1.3).
   *
   * The rulebook asks the moving PLAYER, once the interrupting fire has been
   * resolved: continue, or stop here. A move resolves synchronously in this
   * engine and a commander is consulted once per activation, so the choice is
   * pre-committed on the option instead — the same decision, made a moment
   * earlier, binding for the move. Same trade, and same reason, as
   * StandingEngagement.
   */
  onContact?: "halt" | "press";
  /**
   * This move is a Retreat (9.3.6), not an advance.
   *
   * A flag rather than an ActionKind because the rulebook does not make it
   * one — a Retreat is a Move, with two extra consequences: a further step of
   * morale, and breaking out of a Melee.
   */
  retreat?: boolean;
  /** An indirect fire mission (9.2.2) rather than a direct shot. */
  indirect?: boolean;
  /** A smoke mission (9.2.2.4): no roll, no casualties, a cloud on the map. */
  smoke?: boolean;
}

export interface Commander {
  readonly kind: "human" | "heuristic" | "llm" | "jev";
  readonly name: string;
  /**
   * Choose one of the offered options.
   *
   * Async because a model is; a bot resolves immediately. Returning the id
   * rather than the option keeps the contract narrow — a commander cannot
   * return something that was not offered.
   */
  decide(
    view: SideView,
    options: ActionOption[],
    question: string,
  ): Promise<{ optionId: string; rationale?: string }>;
}

/**
 * A commander with simple, legible priorities.
 *
 * Deliberately NOT clever. Its job is to be a consistent opponent and a
 * yardstick, and a yardstick whose behaviour nobody can predict is not one.
 * The priorities, in order:
 *
 *   1. Assault a broken defender that is already in contact — finish it.
 *   2. Fire at the target where the odds are best, preferring the weakest
 *      enemy in range: concentration beats spreading fire thin.
 *   3. Move towards the nearest contact, if there is somewhere to go.
 *   4. Hold.
 *
 * It never passes while it has an unused force element, which is a real
 * weakness — a good commander holds units back — and is exactly the kind of
 * thing an LLM opponent might beat it on.
 */
/**
 * How hard a commander tries to keep its force together.
 *
 * ⚠ WHY THIS IS A COMMANDER SETTING AND NOT A RULE.
 *
 * Nothing in BGWS obliges a force to stay concentrated. Dispersing is legal,
 * sometimes correct, and the rules charge for it only indirectly — by making
 * Combined Fire unavailable to elements more than 250 m apart. So this is a
 * PREFERENCE, and it belongs to whoever is playing rather than to the
 * ruleset.
 *
 * It exists because the first sweep of `combinedFire` produced a number that
 * could not be interpreted: 186/200 on the one force list that starts
 * concentrated and 14-26/200 on the other four. Both heuristics moved each
 * element independently towards its own nearest contact, so a force scattered
 * past co-location within about two turns and then could not mass even where
 * massing was obviously right. That is a fact about the commander, and
 * reading it as a fact about the rule is exactly the confusion the harness
 * exists to prevent.
 */
export interface FormationPreference {
  /** The distance that makes Combined Fire possible. From the ruleset. */
  coLocatedM: number;
}

export function heuristicCommander(
  side: Side,
  rng: Rng,
  formation?: FormationPreference,
): Commander {
  return {
    kind: "heuristic",
    name: formation ? `formation-${side}` : `heuristic-${side}`,
    async decide(view, options) {
      const scored = options.map((option) => ({
        option,
        score: scoreOption(option, view) + formationBonus(option, view, formation),
      }));

      const best = Math.max(...scored.map((s) => s.score));
      const tied = scored.filter((s) => s.score === best);
      // Ties broken from the seeded generator, so a replay is exact.
      const chosen = tied.length === 1 ? tied[0] : rng.pick(tied);

      return {
        optionId: chosen.option.id,
        rationale: `heuristic score ${chosen.score}`,
      };
    },
  };
}

/**
 * Short range of whichever capability can reach at this distance.
 *
 * Zero when nothing reaches, which makes every shot "long" and so makes
 * closing the preferred option — which is the right answer when you are out
 * of range entirely.
 */
function shortRangeFor(actor: { capabilities: Capability[] }, rangeM: number): number {
  const capability =
    actor.capabilities.find((c) => rangeM <= c.maxRangeM) ??
    actor.capabilities.reduce<Capability | undefined>(
      (best, c) => (best == null || c.maxRangeM > best.maxRangeM ? c : best),
      undefined,
    );
  return capability?.shortRangeM ?? 0;
}

/**
 * Reward a move that ends up beside friends.
 *
 * Deliberately scored on the DESTINATION rather than on the current position:
 * the question is whether this bound keeps the troop together, not whether it
 * is together now.
 *
 * Only moves are scored. Firing already has its own massing bonus, and
 * penalising an element for shooting from where it stands would make the
 * commander refuse good shots to preserve a formation — which is the tail
 * wagging the dog.
 */
function formationBonus(
  option: ActionOption,
  view: SideView,
  formation: FormationPreference | undefined,
): number {
  if (!formation || option.kind !== "move" || !option.destination) return 0;

  const actor = view.own.find((fe) => fe.id === option.actorId);
  const friends = view.own.filter((fe) => fe.id !== option.actorId && fe.combatStrength > 0);
  if (!actor || friends.length === 0) return 0;

  const gapNow = Math.min(...friends.map((fe) => distanceM(fe.position, actor.position)));
  const gapAfter = Math.min(
    ...friends.map((fe) => distanceM(fe.position, option.destination!)),
  );

  // Ending the bound inside co-location is the thing worth having: it is what
  // makes Combined Fire available next turn.
  if (gapAfter <= formation.coLocatedM) return 12;

  // Otherwise, credit for closing the gap at all. Without this a force
  // deployed 500 m apart — which is how every force list deploys — could
  // never begin to concentrate, because the first bound never reaches
  // co-location and so scored nothing.
  if (gapAfter < gapNow) return Math.min(10, Math.round((gapNow - gapAfter) / 50));

  // Capped throughout so that keeping formation influences which way to go
  // without ever outweighing the difference between closing with the enemy
  // and standing still. A commander that would rather huddle than fight is
  // not a better baseline, it is a differently broken one.
  return 0;
}

/**
 * Press on through contact, or go to ground? (7.1.3)
 *
 * ⚠ A TIE IS NOT A DECISION. Both variants of a move scored identically, so the
 * baseline picked between them with the tie-break generator — a coin flip on a
 * question the rulebook hands to the player. That is the same mistake as a rule
 * nothing can reach: the choice existed and nobody was making it, and the
 * randomness showed up as noise in the balance canary.
 *
 * The rule here is deliberately simple, because the baseline's job is to be
 * predictable rather than clever: an element with a march to complete and the
 * morale to complete it presses on; anything shaken, or moving without a plan
 * behind it, goes to ground. A better commander is expected to beat this — that
 * is what the trial is for.
 */
function contactChoiceScore(option: ActionOption, view: SideView): number {
  if (!option.onContact) return 0;
  const actor = view.own.find((fe) => fe.id === option.actorId);
  const steady = actor?.morale === "good" || actor?.morale === "suppressed1";
  const onMission = option.route !== undefined;

  if (option.onContact === "press") return steady && onMission ? 4 : -4;
  return steady && onMission ? -4 : 4;
}

function scoreOption(option: ActionOption, view: SideView): number {
  return baseScore(option, view) + contactChoiceScore(option, view);
}

function baseScore(option: ActionOption, view: SideView): number {
  switch (option.kind) {
    case "assault": {
      // Finishing a shaken defender is worth more than starting a new fight,
      // and going in together beats going in alone — an assault is resolved
      // on the odds ratio, so numbers matter more here than anywhere.
      const contact = view.contacts.find((c) => c.id === option.targetId);
      const together = option.actorIds?.length ?? 1;
      return (contact?.observedMarkers.includes("fired") ? 90 : 80) + (together > 1 ? 5 : 0);
    }
    case "fire": {
      const target = view.contacts.find((c) => c.id === option.targetId);
      if (!target) return 40;
      const actor = view.own.find((fe) => fe.id === option.actorId);
      if (!actor) return 40;

      const rangeM = distanceM(actor.position, target.position);
      const shortRangeM = shortRangeFor(actor, rangeM);

      // CONCENTRATION BEATS SPREADING FIRE THIN, and the fire table is built
      // to say so — its columns are spaced wide enough that two elements
      // firing together are worth considerably more than two firing
      // separately. A baseline that never combined would leave that claim
      // untested, so the bonus scales with how many join in.
      const together = option.actorIds?.length ?? 1;
      const massing = together > 1 ? 8 + together : 0;

      // INSIDE short range, shooting is the best thing on offer.
      if (rangeM <= shortRangeM) {
        return 70 + massing - Math.min(10, Math.round(rangeM / 300));
      }

      // BEYOND it, the shot is available but degraded by the longRange DRM,
      // and is worth LESS than closing the distance first. Before this, fire
      // scored 50-70 against movement's flat 30, so a commander opened fire
      // at maximum range on turn one and never moved again for the rest of
      // the game — which left `targetMoved` and `firerMoved` as declared
      // modifiers that no sequence of play could reach, and made every
      // engagement a static long-range duel.
      return 45 + massing - Math.min(10, Math.round(rangeM / 400));
    }
    case "move": {
      const target = view.contacts.find((c) => c.id === option.targetId);
      const actor = view.own.find((fe) => fe.id === option.actorId);
      if (!target || !actor) return 30;

      const rangeM = distanceM(actor.position, target.position);
      // Closing to short range beats shooting from long range; once inside
      // it, moving is a worse use of the activation than firing.
      return rangeM > shortRangeFor(actor, rangeM) ? 55 : 25;
    }
    case "hold":
      return 10;
    case "pass":
      return 0;
    default:
      return 0;
  }
}

/**
 * A commander that always takes the first option.
 *
 * For tests that care about the loop rather than the choices, and as the
 * control case in an experiment: if a ruleset produces the same outcomes under
 * this as under the heuristic, the decisions were not carrying the game.
 */
export function firstOptionCommander(side: Side): Commander {
  return {
    kind: "heuristic",
    name: `first-option-${side}`,
    async decide(_view, options) {
      return { optionId: options[0].id };
    },
  };
}
