// ── bgws/rules/llmCommander.ts ─────────────────────────────────────────────
// A commander that is a language model.
//
// THE MODEL CALL IS INJECTED, and that is the whole design of this file.
//
// Everything here — building the prompt, parsing the reply, deciding what to
// do with a malformed one — is pure and unit tested. The only impure part is
// a function of shape `(prompt: string) => Promise<string>`, passed in.
//
// This matters for two reasons. It means the prompt and the parser can be
// tested without a model, a network, or a published function. And it means
// the model can be reached however this repo ends up reaching it — a Foundry
// function through the generated OSDK, the pattern `generateOrbatV2` already
// uses in the orbatManager app, or anything else — without this file caring.
//
// WHAT THE MODEL IS AND IS NOT TRUSTED WITH
//
// It is asked to choose among options it was given, by id. It is NOT asked
// where to move, what to fire at, or whether something is in range: every
// legal option was generated by `optionsFor` from the rules, and anything the
// model returns that is not on that list is dropped by `validateOrders`.
//
// So the failure mode of a confused model is a unit that stands still, which
// is visible in the log and on the board — never an illegal move the engine
// tries to honour. A model cannot cheat, only lose.

import { describeForPrompt } from "../lib/fogOfWar";
import type { Side } from "../lib/state";
import type {
  CounteractionOrders,
  CounteractionRequest,
  Intent,
  Orders,
  OrdersCommander,
  OrdersRequest,
  StandingOrder,
} from "./orders";
import type { StandingEngagement } from "./ruleset";

/** The only impure thing. Takes a prompt, returns the model's raw reply. */
export type ModelCall = (prompt: string) => Promise<string>;

export interface LlmCommanderOptions {
  side: Side;
  call: ModelCall;
  /** Free text prepended to every prompt — doctrine, personality, mission. */
  directive?: string;
  /** Shown in logs and on the counter's decision line. */
  name?: string;
}

/**
 * The prompt for one turn.
 *
 * Built to be READ BY A HUMAN as well as a model, because the fastest way to
 * work out why a commander did something stupid is to look at what it was
 * actually told. Anything not in here, it did not know.
 */
export function buildOrdersPrompt(request: OrdersRequest, directive?: string): string {
  const lines: string[] = [];

  lines.push(
    `You command ${request.side.toUpperCase()} forces in a turn-based wargame.`,
    "",
  );
  if (directive?.trim()) lines.push(directive.trim(), "");

  lines.push(
    `TURN ${request.turn}.`,
    "",
    "WHAT YOU CAN SEE",
    "",
    // The same fog-of-war projection the rules use, so the prompt cannot
    // describe something the engine would not let this side act on.
    describeForPrompt(request.view),
    "",
    "YOUR ORDERS THIS TURN",
    "",
    request.activationBudget === Number.POSITIVE_INFINITY
      ? "You may order every element."
      : `COMMAND CAPACITY: ${request.activationBudget} element(s) this turn. ` +
        "Others hold position.\n" +
        "\n" +
        // ⚠ SAY WHAT HAPPENS ON OVERRUN, AND MEAN IT. The validator drops
        // surplus orders from the END of the list. That was true before and
        // undocumented, so a model that led with context and finished with
        // its decisive move lost exactly the order it cared most about. The
        // rule is now part of the contract, which turns an arbitrary clip
        // into a choice this commander is making on purpose.
        "LIST YOUR ORDERS MOST IMPORTANT FIRST. If you give more orders than\n" +
        "your command capacity, the surplus is DROPPED FROM THE END — so the\n" +
        "order you would least mind losing goes last. Ordering an element to\n" +
        "hold costs a full activation and achieves nothing: simply leave out\n" +
        "anything you do not intend to commit.\n" +
        "\n" +
        // ⚠ TELL IT THE SILENCE IS LEGIBLE. Without this the instruction above
        // asks the model to express "these two stay in hand" by saying
        // nothing, which is indistinguishable from forgetting them — and the
        // model knows it, so it either wastes capacity on holds or explains
        // itself in prose the map never shows.
        "Elements you leave out are MARKED UNCOMMITTED on the map, so leaving\n" +
        "one out states a decision rather than losing it. Say in `plan` what\n" +
        "the uncommitted elements are being kept for.",
    "",
    "Choose ONE option per element, by its exact id. These are the only legal",
    "moves — the rules generated them. Anything else will be ignored.",
    "",
  );

  const entries = Object.entries(request.optionsByElement);
  if (entries.length === 0) {
    lines.push("(No element has a decision to make this turn.)");
  }

  for (const [actorId, options] of entries) {
    const own = request.view.own.find((fe) => fe.id === actorId);
    lines.push(
      `${actorId} — ${own?.label ?? "unknown"}` +
        (own
          ? ` (Combat Strength ${own.combatStrength}/${own.combatStrengthStart}, ` +
            `Troop Quality ${own.troopQuality}, morale ${own.morale})`
          : ""),
    );
    for (const option of options) lines.push(`  ${option.id}  ${option.summary}`);
    lines.push("");
  }

  lines.push(
    "STANDING ORDERS (optional, and they matter)",
    "",
    "Each element also has rules of engagement for the turn: whether it answers",
    "an enemy that acts within its arc. You are not asked again when the moment",
    "comes — you decide now and live with it.",
    "",
    '  "never"             hold fire, stay concealed, keep the ammunition',
    '  "ifFiredUpon"       stay quiet until someone engages your side',
    '  "withinShortRange"  answer anything that closes inside short range',
    '  "always"            answer anything you can reach',
    "",
    "Unstated elements use the scenario default. A reaction is a snap shot and",
    "is worse than deliberate fire, so answering everything at maximum range",
    "wastes ammunition and reveals positions. An element that reacts cannot act",
    "again for the rest of the turn, so overwatch is something you assign, not",
    "something you get for free.",
    "",
  );

  if (request.reserveLimit > 0) {
    lines.push(
      "RESERVE (optional, and it is a real trade)",
      "",
      `You may hold up to ${request.reserveLimit} element(s) in reserve this turn.`,
      "",
      "A reserve does NOT fire or assault in this round — that is the price. In",
      "exchange, once both sides have finished, it moves up to 1,000 m towards",
      "where it is needed and may then fire or assault, having seen how the",
      "round actually went. Holding nothing back is a legitimate choice; so is",
      "holding the maximum.",
      "",
    );
  }

  lines.push(
    "REPLY FORMAT",
    "",
    // ⚠ `plan` IS FIRST ON PURPOSE AND IT IS NOT DECORATION. The reply is
    // generated in order, so naming the main effort before listing orders is
    // what makes the orders answer to it rather than the other way round.
    // Nothing reads this field mechanically — it is for the log and for the
    // player — but it still shapes everything written after it.
    "JSON only, no prose, no code fences. Write `plan` FIRST: name your main",
    "effort — which element or pair decides this turn — and what the rest are",
    "there to do. Then list the orders in the priority order it implies.",
    "",
    '{"plan":"main effort: X does Y; Z screens",',
    ' "orders":[{"actorId":"...","optionId":"...","why":"..."}],',
    ' "standingOrders":[{"actorId":"...","engage":"withinShortRange"}],',
    ' "reserves":["actorId"]}',
  );

  return lines.join("\n");
}

/**
 * The prompt for the Counteraction Round (Core Rules 7.2).
 *
 * A SECOND CALL, ASKED AFTER THE FIRST ROUND HAS BEEN FOUGHT, and that is the
 * whole value of it. A reserve committed before seeing what happened is not a
 * reserve, it is a late start; second-round fire chosen in advance cannot
 * answer what the enemy actually did.
 */
export function buildCounteractionPrompt(
  request: CounteractionRequest,
  directive?: string,
): string {
  const lines: string[] = [];

  lines.push(
    `You command ${request.side.toUpperCase()} forces. The main round of turn ` +
      `${request.turn} has been fought.`,
    "",
  );
  if (directive?.trim()) lines.push(directive.trim(), "");

  lines.push("WHAT YOU CAN SEE NOW", "", describeForPrompt(request.view), "");

  const moves = Object.entries(request.reserveMoves);
  const fires = Object.entries(request.fireOptions);

  if (moves.length > 0) {
    lines.push(
      "YOUR RESERVE CAN MOVE UP",
      "",
      "Up to 1,000 m towards where it is needed. It may fire or assault at the",
      "end of that move.",
      "",
    );
    for (const [actorId, options] of moves) {
      const own = request.view.own.find((fe) => fe.id === actorId);
      lines.push(`${actorId} — ${own?.label ?? "unknown"}`);
      for (const option of options) lines.push(`  ${option.id}  ${option.summary}`);
    }
    lines.push("");
  }

  if (fires.length > 0) {
    lines.push(
      "ANYTHING THAT HAS NOT FIRED THIS TURN MAY FIRE NOW",
      "",
      "A second-round shot is worse than a first-round one, so this is what you",
      "kept in hand rather than a free extra volley.",
      "",
    );
    for (const [actorId, options] of fires) {
      const own = request.view.own.find((fe) => fe.id === actorId);
      lines.push(`${actorId} — ${own?.label ?? "unknown"}`);
      for (const option of options) lines.push(`  ${option.id}  ${option.summary}`);
    }
    lines.push("");
  }

  if (moves.length === 0 && fires.length === 0) {
    lines.push("(Nothing is available to you. Reply with an empty list.)", "");
  }

  lines.push(
    "PASSING IS FINAL. Once you stop firing you cannot change your mind later",
    "in this round, even after seeing what the enemy does. List every option",
    "you want, in the order you want them taken; anything left out is a pass.",
    "",
    "REPLY FORMAT",
    "",
    "JSON only, no prose, no code fences:",
    '{"plan":"one sentence","optionIds":["...","..."]}',
  );

  return lines.join("\n");
}

const ENGAGEMENTS: StandingEngagement[] = [
  "never",
  "ifFiredUpon",
  "withinShortRange",
  "always",
];

export interface ParsedOrders {
  plan?: string;
  intents: Intent[];
  standingOrders: StandingOrder[];
  /** Elements the model wants held back. Capped later by nominateReserves. */
  reserves: string[];
  /** Set when the reply could not be read at all. */
  parseError?: string;
}

/**
 * Read a model's reply.
 *
 * Tolerant by design: models wrap JSON in fences, add a sentence before it,
 * or return a bare array. None of that is worth losing a turn over, and a
 * strict parser would make the commander's quality indistinguishable from its
 * formatting discipline.
 *
 * What it will NOT do is guess an option id. A missing or unrecognised id is
 * dropped by validateOrders, which is where that judgement belongs.
 */
export function parseOrdersReply(reply: string): ParsedOrders {
  const text = reply.trim();
  if (!text) return { intents: [], standingOrders: [], reserves: [], parseError: "empty reply" };

  // Strip a code fence if there is one, then take the outermost JSON value.
  const unfenced = text.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  const start = unfenced.search(/[[{]/);
  if (start === -1) return { intents: [], standingOrders: [], reserves: [], parseError: "no JSON found" };

  const opensWithArray = unfenced[start] === "[";
  const end = unfenced.lastIndexOf(opensWithArray ? "]" : "}");
  if (end <= start) {
    return { intents: [], standingOrders: [], reserves: [], parseError: "unterminated JSON" };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(unfenced.slice(start, end + 1));
  } catch (err) {
    return {
      intents: [],
      standingOrders: [],
      reserves: [],
      parseError: err instanceof Error ? err.message : "bad JSON",
    };
  }

  const rawOrders = Array.isArray(parsed)
    ? parsed
    : isRecord(parsed) && Array.isArray(parsed.orders)
      ? parsed.orders
      : null;

  if (rawOrders == null) {
    return { intents: [], standingOrders: [], reserves: [], parseError: "no orders array" };
  }

  const intents: Intent[] = [];
  for (const entry of rawOrders) {
    if (!isRecord(entry)) continue;
    const actorId = typeof entry.actorId === "string" ? entry.actorId : undefined;
    const optionId = typeof entry.optionId === "string" ? entry.optionId : undefined;
    if (!actorId || !optionId) continue;
    intents.push({
      actorId,
      optionId,
      rationale: typeof entry.why === "string" ? entry.why : undefined,
    });
  }

  // Standing orders are optional and independently malformed-tolerant: a
  // commander that gets its orders right and its ROE wrong should still get
  // its orders.
  const standingOrders: StandingOrder[] = [];
  const rawStanding =
    isRecord(parsed) && Array.isArray(parsed.standingOrders) ? parsed.standingOrders : [];
  for (const entry of rawStanding) {
    if (!isRecord(entry)) continue;
    const actorId = typeof entry.actorId === "string" ? entry.actorId : undefined;
    const engage = ENGAGEMENTS.find((known) => known === entry.engage);
    if (!actorId || !engage) continue;
    standingOrders.push({
      actorId,
      engage,
      withinM: typeof entry.withinM === "number" ? entry.withinM : undefined,
    });
  }

  // Reserves are just ids. Over-nominating is capped by nominateReserves
  // rather than rejected here: holding back more than a third is a planning
  // error, not an attempt to cheat, and silently trimming it to the legal
  // maximum is what an umpire would do.
  const reserves: string[] = [];
  const rawReserves =
    isRecord(parsed) && Array.isArray(parsed.reserves) ? parsed.reserves : [];
  for (const entry of rawReserves) {
    if (typeof entry === "string") reserves.push(entry);
    else if (isRecord(entry) && typeof entry.actorId === "string") reserves.push(entry.actorId);
  }

  const plan = isRecord(parsed) && typeof parsed.plan === "string" ? parsed.plan : undefined;
  return { plan, intents, standingOrders, reserves };
}

/**
 * Read a model's Counteraction Round reply.
 *
 * Deliberately separate from `parseOrdersReply` and deliberately simpler: the
 * round only ever asks for a list of option ids in preference order. A reply
 * that cannot be read is a PASS, which is a legal move — so unlike the orders
 * phase there is nothing to report as an error, only a plan line saying what
 * happened.
 */
export function parseCounteractionReply(reply: string): CounteractionOrders["optionIds"] {
  const text = reply.trim();
  if (!text) return [];

  const unfenced = text.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
  const start = unfenced.search(/[[{]/);
  if (start === -1) return [];

  const opensWithArray = unfenced[start] === "[";
  const end = unfenced.lastIndexOf(opensWithArray ? "]" : "}");
  if (end <= start) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(unfenced.slice(start, end + 1));
  } catch {
    return [];
  }

  const raw = Array.isArray(parsed)
    ? parsed
    : isRecord(parsed) && Array.isArray(parsed.optionIds)
      ? parsed.optionIds
      : [];

  const ids: string[] = [];
  for (const entry of raw) {
    if (typeof entry === "string") ids.push(entry);
    else if (isRecord(entry) && typeof entry.optionId === "string") ids.push(entry.optionId);
  }
  return ids;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * A commander backed by a model.
 *
 * A failed call does NOT fail the turn. The side holds position, the reason
 * is recorded on the orders as the plan, and the game continues — because a
 * proxy 403 or a rate limit should not throw away an engagement in progress,
 * and "red held because the model was unreachable" is a legible outcome.
 */
export function llmCommander(options: LlmCommanderOptions): OrdersCommander {
  return {
    kind: "llm",
    name: options.name ?? `llm-${options.side}`,
    async planTurn(request: OrdersRequest): Promise<Orders> {
      const prompt = buildOrdersPrompt(request, options.directive);

      let reply: string;
      try {
        reply = await options.call(prompt);
      } catch (err) {
        const reason = err instanceof Error ? err.message : String(err);
        return {
          side: request.side,
          intents: [],
          plan: `model unreachable — held position (${reason})`,
          failure: `unreachable: ${reason}`,
        };
      }

      const parsed = parseOrdersReply(reply);
      if (parsed.parseError) {
        return {
          side: request.side,
          intents: [],
          plan: `model reply unreadable — held position (${parsed.parseError})`,
          failure: `unreadable: ${parsed.parseError}`,
        };
      }

      return {
        side: request.side,
        intents: parsed.intents,
        standingOrders: parsed.standingOrders,
        reserves: parsed.reserves,
        plan: parsed.plan,
      };
    },

    async planCounteraction(request: CounteractionRequest): Promise<CounteractionOrders> {
      // Nothing on offer is not worth a model call. The Counteraction Round
      // is frequently empty for one side, and paying for a round trip to be
      // told so would double the cost of a turn for nothing.
      const empty =
        Object.keys(request.reserveMoves).length === 0 &&
        Object.keys(request.fireOptions).length === 0;
      if (empty) return { side: request.side, optionIds: [] };

      const prompt = buildCounteractionPrompt(request, options.directive);

      let reply: string;
      try {
        reply = await options.call(prompt);
      } catch (err) {
        // A pass, not a crash — same reasoning as an unreachable model in the
        // orders phase, and here it is an ordinary legal move.
        return {
          side: request.side,
          optionIds: [],
          plan: `model unreachable — passed (${
            err instanceof Error ? err.message : String(err)
          })`,
        };
      }

      const optionIds = parseCounteractionReply(reply);
      return {
        side: request.side,
        optionIds,
        plan: optionIds.length === 0 ? "passed the counteraction round" : undefined,
      };
    },
  };
}

/**
 * The stub used until a model function is published.
 *
 * Throws with instructions rather than returning something plausible. A
 * commander that quietly held every turn would look like a cautious model
 * rather than a missing one, and someone would spend an afternoon tuning a
 * prompt that was never sent anywhere.
 */
export const unavailableModelCall: ModelCall = async () => {
  throw new Error(
    "No model is wired up. The LLM commander needs a Foundry function that " +
      "wraps a language model — the same pattern as generateOrbatV2 in the " +
      "orbatManager app — published, with the SDK regenerated. Until then, " +
      "choose the heuristic commander.",
  );
};
